### ISSUE TITLE
request to make ContinuationPar and NewtonPar mutable

### ISSUE THREAD

**Issue by gszep** [rveltz/PseudoArcLengthContinuation.jl#11]
Requesting to make these structures mutable so that it would be possible to update hyperparameters during optimisation loops.
```julia
parameters = ContinuationPar() # inital hyperparameters

for i=1:10 # some optimisation loop
       parameters.ds *= i*parameters.ds # for example changing ds
end
```
throws `ERROR: setfield! immutable struct of type ContinuationPar cannot be changed`

**Comment by gszep** [comment]
ok I can see you introduced `@set` decorators. What should I do if I want to `deepcopy(parameters)`?

**Comment by rveltz** [comment]
Hi

This is tricky to change :) 

I did this in order to have an [iterator](https://rveltz.github.io/PseudoArcLengthContinuation.jl/dev/iterator/) and having it type stable was not a piece of cake.

The way to do this is to use the iterator interface because `PALCStateVariables ` is mutable.

A less intrusive way is to use the callbacks `finalizeSolution` and `callbackC`. I chose not to expose the iterator in these callbacks because I wanted them to be simple. If you want I can make them expose the iterator using the `kwargs`.

> Sorry for my slow response time, for some reason, I do not get notifications by github for the issues

**Comment by gszep** [comment]
so I'm using this kind of loop which seems to work fine!
```julia
for i=1:length(u) # iterate through list of roots
	for (pMin,pMax) in intervals # compute forwards and backwards branches from root

		parameters = setproperties(parameters; 
                        pMin=p[i]+pMin, pMax=p[i]+pMax,
			ds=sign(parameters.ds)*ds)

		branch = Branch(Vector{T}[],T[],[]) # custom branch struct
		iterator = PALCIterable( f, J, u[i], p[i], parameters)

		for state in iterator
			push!(branch.state,copy(getx(state)))
			push!(branch.parameter,copy(getp(state)))
		end

	        push!(branches,branch)
                parameters = @set parameters.ds = -parameters.ds
	end
end
```
In the docs you have `getx(state)` instead of `copy(getx(state))`. But without the copy statement I get constant arrays coming out. Is this correct?

**Comment by gszep** [comment]
In the docs you have `getx(state)` instead of `copy(getx(state))`. But without the copy statement I get constant arrays coming out. Is this correct?

**Comment by rveltz** [comment]
`getp` is a scalar, so it is not a reference. However, I need this copy for the array `getx` to prevent the unexperienced user from breaking the algorithm

**Comment by gszep** [comment]
all clear! closing this issue as it was resolved

**Comment by rveltz** [comment]
Cool
