### ISSUE TITLE
Trouble with branch switching and matrix-free

### ISSUE THREAD

**Issue by antoine-levitt** [rveltz/PseudoArcLengthContinuation.jl#16]
```julia
using PseudoArcLengthContinuation, LinearAlgebra, Plots
const PALC = PseudoArcLengthContinuation
using ForwardDiff
using Parameters, Setfield

function f(x, p)
    [p.α*x[1] + x[1]^3 ]
end
function Jf(x, p)
    Jf = zeros(1, 1)
    Jf[1] = p.α+3x[1]^2
    dx -> Jf*dx
end

# eigensolver
struct MyStruct <: PALC.AbstractEigenSolver
end
function (m::MyStruct)(J, nev)
    return [(J(1))[1]], [1.], true, 1
end

Fmit = f
D(f, x, p, dx) = ForwardDiff.derivative(t->f(x .+ t .* dx, p), 0.)
function D(f, x, p, dx)
    ε=1e-10
    (f(x + ε*dx, p) - f(x, p))/ε
end
d1Fmit(x,p,dx1) = D((z, p0) -> Fmit(z, p0), x, p, dx1)
d2Fmit(x,p,dx1,dx2) = D((z, p0) -> d1Fmit(z, p0, dx1), x, p, dx2)
d3Fmit(x,p,dx1,dx2,dx3) = D((z, p0) -> d2Fmit(z, p0, dx1, dx2), x, p, dx3)
jet = (f, d1Fmit, d2Fmit, d3Fmit)
jet = (f, Jf, d2Fmit, d3Fmit)

alpha_min = -10.
alpha_max = 10.
alpha_start = 2.

# options for Newton solver
opt_newton = PALC.NewtonPar(tol = 1e-8, verbose = true, maxIter = 20, eigsolver = MyStruct())
# opt_newton = PALC.NewtonPar(tol = 1e-8, verbose = true, maxIter = 20, eigsolver = MyStruct(), linsolver=GMRESKrylovKit())

# options for continuation
opts_br = ContinuationPar(dsmin = 0.001, dsmax = 0.05, ds = -0.01, pMax = alpha_max, pMin = alpha_min,
	                  detectBifurcation = 2, nev = 30, plotEveryNsteps = 10, newtonOptions = opt_newton,
	                  maxSteps = 100, precisionStability = 1e-6, nInversion = 4, dsminBisection = 1e-7, maxBisectionSteps = 25)

sol_start, _, _ = newton( f, [1.], (α=.1,), opt_newton)
par_mit = (α=alpha_start,)

br, _ = @time PALC.continuation(
    Fmit, Jf,
    sol_start, par_mit, (@lens _.α), opts_br;
    # printSolution = (x, p) -> norm(x),
    # plotSolution = (x, p; kwargs...) -> plotsol!(x ; kwargs...),
    plot = false, verbosity = 3)

br2, _ = continuation(jet..., br, 1, setproperties(opts_br, ds = -0.01, maxSteps = 20), plot = false, printSolution = (x,p) -> x[1], verbosity=3, Jt=Jf)
br3, _ = continuation(jet..., br, 1, setproperties(opts_br, ds = 0.01, maxSteps = 20), plot = false, printSolution = (x,p) -> x[1], verbosity=3, Jt=Jf)

Plots.plot([br,br2,br3])
```
doesn't work. It does if I uncomment the opt_newton line setting the linear solver. I mention this as a bug because the continuation (without branch switching) seems to work fine, meaning it probably autodetects that the problem is matrix-free but branch switching doesn't?

**Comment by rveltz** [comment]
I think I understand the problem. If you stay at the level of `newton`, you can already see this. If I do 

```
sol_start, _, _ = newton( f, [1.], (α=.1,), opt_newton)
```
it works because `newton` generates a **matrix based version** of the jacobian, however it does this whatever the linear solver passed. Hence, if you do 

```
sol_start, _, _ = newton( f, Jf, [1.], (α=.1,), opt_newton)
```
it errors. I guess the docs of `newton` is misleading. Now I can see your point. If `NewtonPar` has a `linsolve` which is matrix-free and the jacobian is not passed, `newton` should generate a Matrix-free version of the jacobian. Which leaves two options:
1. I update the docs of `newton` to makes this story clearer
2. I implement the automatic generation of `J`, probably with traits.
3. generates a matrix jacobian even if a MF jacobian is passed when `NewtonPar.linsolver` is a `DefaultLS`

My point of view is to go for 1. as 2. would be an overkill just to generate a bad jacobian. If you are already at the stage of using Matrix-Free methods, you should.

**Comment by antoine-levitt** [comment]
I'm confused, what do you mean to generate a matrix based version? It calls the matrix free jacobian to compute a dense jacobian by calling it on all the columns? If that is the case I'd rather it errors rather than doing that...

**Comment by rveltz** [comment]
When you dont pass the jacobian, `newton` (and `continuation`) method is overload to this 

```
function newton(Fhandle, x0, p0, options::NewtonPar; kwargs...)
	Jhandle = (u, p) -> finiteDifferences(z -> Fhandle(z, p), u)
	return newton(Fhandle, Jhandle, x0, p0, options; kwargs...)
end
```

where [finiteDifferences](https://github.com/rveltz/PseudoArcLengthContinuation.jl/blob/master/src/Utils.jl#L70) is shown here. To me, this is more a conveniency not to scare away the inexperience user. However, apart from the beginning of the first tutorials, I never used it.

Maybe I should remove these methods altogether.

> However concerning the inadequacy of solver and jacobian, I like your remark. I am not sure whther to do this in a way that does not burn too much performance, the code would be length (I think).

**Comment by antoine-levitt** [comment]
Alright when you don't pass a jacobian at all then it makes sense to do it with finite differences; but when you pass a matrix-free jacobian you probably mean to use a matrix-free linear solver

**Comment by rveltz** [comment]
> when you pass matrix-free jacobian you probably mean to use a matrix-free linear solver

To me the best in this case is to emit a proper error instead of providing a default MF linearsolver. I can ask for type enforcement like this 

```
# I added the ::AbstractMatrix
function (l::DefaultLS)(J::AbstractMatrix, rhs1, rhs2; a₀ = 0, a₁ = 1, kwargs...)
	if l.useFactorization
		Jfact = factorize(_axpy(J, a₀, a₁))
		return Jfact \ rhs1, Jfact \ rhs2, true, (1, 1)
	else
		return J \ rhs1, J \ rhs2, true, (1, 1)
	end
end
```

Indeed, as of now, the error is not precise enough, it says 

```
ERROR: MethodError: no method matching adjoint(::var"#65#66"{Array{Float64,2}})
Closest candidates are:
  adjoint(::Missing) at missing.jl:100
  adjoint(::Number) at number.jl:193
  adjoint(::Adjoint{#s162,#s161} where #s161<:Union{StaticArrays.StaticArray{Tuple{N},T,1} where T where N, StaticArrays.StaticArray{Tuple{N,M},T,2} where T where M where N} where #s162) at /Users/rveltz/.julia/packages/StaticArrays/mlIi1/src/linalg.jl:73
  ...
Stacktrace:
 [1] \(::Function, ::Array{Float64,1}) at ./operators.jl:563
 [2] #_#5(::Int64, ::Int64, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::DefaultLS, ::Function, ::Array{Float64,1}) at /Users/rveltz/work/prog_gd/julia/dev/dev1/PseudoArcLengthContinuation.jl/src/LinearSolver.jl:71
 [3] (::DefaultLS)(::Function, ::Array{Float64,1}) at /Users/rveltz/work/prog_gd/julia/dev/dev1/PseudoArcLengthContinuation.jl/src/LinearSolver.jl:71
 [4] #newton#55(::typeof(norm), ::Function, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(newton), ::typeof(f), ::typeof(Jf), ::Array{Float64,1}, ::NamedTuple{(:α,),Tuple{Float64}}, ::NewtonPar{Float64,DefaultLS,MyStruct}) at /Users/rveltz/work/prog_gd/julia/dev/dev1/PseudoArcLengthContinuation.jl/src/Newton.jl:110
 [5] newton(::Function, ::Function, ::Array{Float64,1}, ::NamedTuple{(:α,),Tuple{Float64}}, ::NewtonPar{Float64,DefaultLS,MyStruct}) at /Users/rveltz/work/prog_gd/julia/dev/dev1/PseudoArcLengthContinuation.jl/src/Newton.jl:89
 [6] top-level scope at none:0

```

**Comment by antoine-levitt** [comment]
Yes I ran into that error also :-)

**Comment by rveltz** [comment]
Actually I am hesitant about restricting the type of `(l::DefaultLS)`. I will put a warning in the docs of `newton` and `continuation` about this. Should I close this?

**Comment by antoine-levitt** [comment]
Sure!
