### ISSUE TITLE
How to use iterator to make a bifurcation diagram?

### ISSUE THREAD

**Issue by TorkelE** [rveltz/PseudoArcLengthContinuation.jl#18]
Hello,
I am following the instructions under https://rveltz.github.io/PseudoArcLengthContinuation.jl/dev/iterator/ to make a bifurcation diagram of a system I am investigating. While I can get the base example to work by running it, I have problems making it work as I'd like for a more general system (and when it works, I am a bit uncertain why).

In the example, I am using `DiffEqBiological` to generate a model, from which I then generate the system function and jacobian. The model equation is
dX/dt = v0 + v*(X^n)/(K^n + X^n) - d*X
and I want to plot the value of the system's fixed point(s) as the parameter v varies from 0.1 to 5.0.
Please see the following code:
```julia
# Fetch stuff
using PseudoArcLengthContinuation, SparseArrays, LinearAlgebra, Plots, Setfield, UnPack
const PALC = PseudoArcLengthContinuation
using DiffEqBiological # Required to generate my system

# Taken from the docs. Don't know why we are doing this.
normInf = x -> norm(x, Inf)

# Generates my functions
# A reactio network. This generates the stuff for a model system with a single variable and 5 parameters.
rn = @reaction_network begin
	v0+hill(X,v,K,n), 0 --> X
	d, X --> 0
end v0 v K n d

# The reaction network structures contain the right functions, however, they are designed for DifferentialEquations and requires modification.
# The original functions do not return the output, but rather modifes an input vector/matrix with the desired values. Also, the parameters works differently (I tried it the natural way, ran into problems, but I will worry about that when I got the main methodology working).
function F(x,p)
	@unpack v0,v,K,n,d = p
	output = copy(x)
	rn.f(output,x,[v0, v, K, n, d],0.)
	return output
end
function J(x,p)
	@unpack v0,v,K,n,d = p
	output = zeros(length(x),length(x))
	rn.jac(output,x,[v0, v, K, n, d],0.)
	return output
end

# Just taken from the docs. I modified pMin and pMax to 0.1 and 10.0. I sat pMin to 0.1 because that was my best guess at the initial value.
opts = PALC.ContinuationPar(dsmax = 0.1, dsmin = 1e-5, ds = -0.001, maxSteps = 130, pMin = 0.1, pMax = 10.0, saveSolEveryNsteps = 0, computeEigenValues = true, detectBifurcation = true, newtonOptions = NewtonPar(tol = 1e-8, verbose = true))

# Set the parameters. I sat v to 5. because I thought that might be the final value.
pars = (v0=0.1, v=5., K=0.5, n=3., d=1.2)

# Tries to define the iterator. The fixed point of the system for v=0.1 is 0.08333333333333334.
iter = PALC.PALCIterable(F, J, [0.08333333333333334], pars, (@lens _.v), opts; verbosity = 2)

# This is just taken directly from the example.
resp = Float64[]
resx = Float64[]
for state in iter
	push!(resx, getx(state)[1])
	push!(resp, getp(state))
end

#This plot
plot(resp, resx; label = "", xlabel = "v")
```
Now, this plot gets rather "jagged", and I'd like it smoother. I try setting 
```
opts = PALC.ContinuationPar(dsmax = 0.01, dsmin = 1e-3, ds = -0.001, maxSteps = 1300,...
```
but this makes the end result weird. I try modifying `ds = 0.001`, but that makes things worse. What should I do here?

Also, could someone confirm how I set the initial and final values of the parameter, as well as exactly where I should make my initial x0 guess? I got it right here, but I would like to be sure why I am right.

Looking forward to getting this working!
Cheers

**Comment by rveltz** [comment]
The docs is misleading for several reasons and I apologize. First, you don't need to define the norm. PALC will use `norm` if not specified. This is useful for PDE problems where you want to pass a specific norm or dot product.

Second, the iterator interface is minimalist: it just perform arclength continuation. It does not compute eigenvalues nor perform bifurcation detection. Hence, in the options, `computeEigenvalues, detectBifurcation ` will be ignored.

I'll get back to you asap for the issue.

**Comment by rveltz** [comment]
I think you can do 

```
function F(x,p)
	output = copy(x)
	rn.f(output,x,p,0.)
	return output
end
```
Your guess does not seem that good: `F([0.08333333333333334], pars) = [0.0230]`. 

I you want to have more points, descrease `dsmax`. Finally, the options `tangentAlgo = BorederedPred()` is "better"

```

# Just taken from the docs. I modified pMin and pMax to 0.1 and 10.0. I sat pMin to 0.1 because that was my best guess at the initial value.
opts = PALC.ContinuationPar(dsmax = 0.05, dsmin = 1e-5, ds = -0.001, maxSteps = 200, pMin = 0.1, pMax = 10.0, saveSolEveryNsteps = 0, newtonOptions = NewtonPar(tol = 1e-8, verbose = true, maxIter = 15))

# Set the parameters. I sat v to 5. because I thought that might be the final value.
pars = (v0=0.1, v=5., K=0.5, n=3., d=1.2)

# Tries to define the iterator. The fixed point of the system for v=0.1 is 0.08333333333333334.
iter = PALC.PALCIterable(F, J, [4.24], pars, (@lens _.v), opts; verbosity = 1, tangentAlgo = BorderedPred())

# This is just taken directly from the example.
resp = Float64[]
resx = Float64[]
for state in iter
	push!(resx, getx(state)[1])
	push!(resp, getp(state))
end

#This plot
plot(resp, resx; label = "", xlabel = "v")
```

**Comment by TorkelE** [comment]
Thank you, I am not sure why reducing `dsmax` messed up the methods in my case, but using your code, and the choice of `tangentAlgo` solves that. I think I mistook the u0 guess, I selected that for the value of  `0.1`, instead of `5.0`. Could you confirm again how I properly should select the start and end points of the iteration?

Also, if I want to compute eigenvalues, as well as to detect bifurcation points, what should I use instead of the iterable? Continuation?

**Comment by TorkelE** [comment]
Had a thought, and maybe I have understood how the selection of the interval works now:
- The value of `pars` that I give to the iterator is the starting value of the tracking.
- The algorithm will continue tracking the solution until it reaches either the `pMin` or `pMax` value.
Is that correct? The only thing would be, in which "direction" does the tracking start? is it determined by the sign of `ds = -0.001`?

**Comment by rveltz** [comment]
> The value of pars that I give to the iterator is the starting value of the tracking

yes

> The algorithm will continue tracking the solution until it reaches either the pMin or pMax value.
Is that correct?

yes

> is it determined by the sign of ds = -0.001

yes


> Also, if I want to compute eigenvalues, as well as to detect bifurcation points, what should I use instead of the iterable? Continuation?

yes `continuation`

Why did you chose the iterable way in the first place?

**Comment by TorkelE** [comment]
Great, thanks for that!

> Why did you chose the iterable way in the first place?

About that the divines still argue, not even sure myself. I think when I looked through the documentation that was the one which stroke me as easy to use, and doing what I wanted to. WIll continue with continuation.

**Comment by rveltz** [comment]
should I close the issue?

**Comment by TorkelE** [comment]
Yes.
