### ISSUE TITLE
plotBranch() shows incorrect fold locations for negative u

### ISSUE THREAD

**Issue by gszep** [rveltz/PseudoArcLengthContinuation.jl#5]
`plotBranch` seems to plot `normC = u -> norm(u)` even if `plotsolution = u -> u[1]`
![Screenshot from 2019-10-19 14-33-50](https://user-images.githubusercontent.com/17977117/67146140-eba8fe00-f27f-11e9-844b-ecdffb6fdad5.png)

**Comment by gszep** [comment]
its probably more user friendly to have both a `plotsolution` for visualisation and a `recordsolution` for recording `AbstractArray{T,N}` types?

**Comment by rveltz** [comment]
This mistake should be corrected on master by now. Thank you for reporting it. 

Are you suggesting to have the keywords `printsolution, recordsolution, plotsolution`?
You might be right. `printsolution` should be called `recordsolution` and we change `printsolution` to `plotsolution`. Would it make more sense?

**Comment by gszep** [comment]
it would be useful to have `recordsolution` safely output an `AbstractArray{T,N}` too
