### ISSUE TITLE
user wants recordfunction kwarg

### ISSUE THREAD

**Issue by gszep** [rveltz/PseudoArcLengthContinuation.jl#6]
it would be useful to be able to record vectors of solutions during continuation method. Suppose I am interested in recording the first and third component of my ode system then I would call
```julia
Cont.continuation( .... recordfunction = u -> [ u[1], u[3] ] )
```
If `u` contained a spatial system then a more interesting `recordfunction` call could be to segment out a pattern and record some statistics on that pattern.. a fourier transform perhaps?
this should not interfere with `printsolution` or `plotBranch`

**Comment by rveltz** [comment]
Note that there is the function `finaliseSolution` which gives you access at the state of the continuation loop at each step. You can thus create your own data structure to save what you want.
Is it what you are suggesting?

It does not affect plotting which is done by using the perhaps misleading name `printsolution`

**Comment by gszep** [comment]
thank you. I was not aware this was possible.. rtfd :man_facepalming:
