### ISSUE TITLE
vscode linter complains about missing DefaultLS,DefaultEig

### ISSUE THREAD

**Issue by gszep** [rveltz/PseudoArcLengthContinuation.jl#7]
it seems to be ok with `ContResult` though!

**Comment by rveltz** [comment]
As a warning?

**Comment by gszep** [comment]
![Screenshot from 2019-10-21 08-52-38](https://user-images.githubusercontent.com/17977117/67187032-3ee69200-f3e1-11e9-9688-c7634c7d0d0e.png)
![Screenshot from 2019-10-21 09-00-02](https://user-images.githubusercontent.com/17977117/67187037-40b05580-f3e1-11e9-9f25-1ce1f8df303c.png)

**Comment by gszep** [comment]
adding you package via `Pkg.add` rather than `Pkg.clone` and using the default environment under `~/.julia` fixed the issue
```julia
using Pkg
Pkg.add(PackageSpec(url="git@github.com:rveltz/PseudoArcLengthContinuation.jl.git"))
```
